version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: dragonwater-mysql
    restart: always
    env_file:
      - .env
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u${DB_USERNAME}", "-p${DB_PASSWORD}"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

  redis:
    image: redis:7.2
    container_name: dragonwater-redis
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 5s

  app:
    image: dragonwater-app:1.0
    container_name: dragonwater-app
    restart: unless-stopped
    env_file:
      - .env
    environment:
      JAVA_TOOL_OPTIONS: "-Xms512m -Xmx2048m"
      TZ: "Asia/Seoul"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - "8080:8080"

volumes:
  mysql_data:
  redis_data: