spring:
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?allowPublicKeyRetrieval=true&useSSL=false
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
        show_sql: false

  cloud:
    aws:
      credentials:
        access-key: ${AWS_ACCESS_KEY}
        secret-key: ${AWS_SECRET_KEY}
      region:
        static: ap-northeast-2
      s3:
        bucket: ${AWS_S3_BUCKET}

  data:
    redis:
      host: redis
      port: 6379

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.hibernate: ERROR

# 토큰 관련 설정
jwt:
  issuer: ${JWT_ISSUER}
  secret-key: ${JWT_SECRET_KEY}

nicepayments:
  mid: ${NICEPAY_MID}
  merchant-key: ${NICEPAY_MERCHANT_KEY}
  client-key: ${NICEPAY_CLIENT_KEY}
  secret-key: ${NICEPAY_SECRET_KEY}

naver:
  object-storage:
    region: kr-standard
    endpoint: https://kr.object.ncloudstorage.com
    bucket-name: dragoncompany-cloudstorage
  sms:
    server-id: ${NAVER_SMS_SERVER_ID}
    phone: ${NAVER_SMS_PHONE}
  access-key: ${NAVER_ACCESS_KEY}
  secret-key: ${NAVER_SECRET_KEY}

ppurio:
  api:
    key: ${PPURIO_API_KEY}
  account: ${PPURIO_ACCOUNT}
  sender-profile: ${PPURIO_SENDER_PROFILE}
  template-code:
    to-customer: ${PPURIO_TEMPLATE_CODE_TO_CUSTOMER}
    to-admin: ${PPURIO_TEMPLATE_CODE_TO_ADMIN}
